aa_website/urls.py
from django.contrib import admin
from django.urls import path,include
from info_app import views

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path('',include('info_app.urls',namespace='info_app'))
]

info_app/urls.py
from django.urls import path
from info_app import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'info_app'

urlpatterns = [
    path('about/',views.view_about.as_view(),name='about'),
    path('repairs/',views.view_repairs.as_view(),name='repairs'),
    path('tires/',views.view_tires.as_view(),name='tires'),
    path('signup/',views.view_signup.as_view(),name='signup'),
    path('inventory/',views.view_carslist.as_view(),name='carlist'),
    path('inventory/<int:pk>/',views.view_cardetails.as_view(),name='cardetails'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info_app/models.py
from django.db import models

# Create your models here.
# Create your models here.
class model_cars(models.Model):
    model = models.CharField(max_length=128)
    make = models.CharField(max_length=128)
    year = models.CharField(max_length=128)
    price = models.CharField(max_length=128)
    mileage = models.CharField(max_length=128)
    engine = models.CharField(max_length=128)
    transmission = models.CharField(max_length=128)
    vin = models.CharField(max_length=128)
    MSRP = models.CharField(max_length=128)
    savings = models.CharField(max_length=128)
    moreinfo = models.TextField(max_length=2048)
    headpic = models.ImageField()

    def __str__(self):
        return self.model

    def get_absolute_url(self):
        return reverse("info_app:detail",kwargs={'pk':self.pk})

class model_carspic(models.Model):
    pic = models.ImageField()
    car = models.ForeignKey(model_cars,models.CASCADE,related_name='carpic')
    def __str__(self):
            return str(self.car)

info_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy,reverse
from django.views.generic import (View,TemplateView,ListView,DetailView)

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class view_repairs(TemplateView):
    template_name = 'info_app/repairs.html'

class view_tires(TemplateView):
    template_name = 'info_app/tires.html'

class view_about(TemplateView):
    template_name = 'info_app/about.html'

class view_signup(TemplateView):
    template_name = 'info_app/signup.html'

class view_carslist(ListView):
    context_object_name = 'car_list'
    model = models.model_cars
    template_name = 'info_app/car_list.html'

class view_cardetails(DetailView):
    context_object_name = 'car_details'
    model = models.model_cars
    template_name = 'info_app/detail.html'

info_app/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>
    {% block title_block %}

    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://hammerjs.github.io/dist/hammer.js"></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block style_block %}

  {% endblock %}
  <link rel="stylesheet" href="{% static 'info_app/css/base.css' %}">

</head>

<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class='logobar text-center' style="background:#0B1B32;">
<a href="{% url 'index' %}" id="aalogo"><img src="{% static 'info_app/images/logocrop.png' %}" alt=""></a>
</div>

<nav class="navbar navbar-expand-md navbar-fixed-top navbar-dark main-nav">
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#RHCCnavbar" aria-controls="RHCCnavbar" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse"  id="RHCCnavbar">
  <ul class="nav navbar-nav mx-auto">
    <li class="nav item ">
      <a class='nav-link' href="{% url 'info_app:about' %}">About</a>
    </li>
    <li class="nav item ">
      <a class='nav-link' href="{% url 'info_app:repairs' %}">Repairs</a>
    </li>
    <li class="nav item ">
      <a class='nav-link' href="{% url 'info_app:tires' %}">Tires</a>
    </li>
    <li class="nav item" id="carlistnav">
      <a class='nav-link' href="{% url 'info_app:carlist' %}">Inventory</a>
    </li>
    <li>
    <li class="nav-item dropdown ">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Contact
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a href="https://www.facebook.com/St.JoeAvenueAutoSales/" target="_blank" id='fblogo'>
        <img class="center-block img-responsive" src="{% static 'info_app/images/Facebook_logo.png' %}" alt="No image"></a>
        <div class="dropdown-divider"></div>
        <p><a href="http://maps.google.com/?q=4202 St Joseph Ave, St Joseph, MO 64505" target="_blank">4202 St Joseph Ave, St Joseph, MO 64505</a> <br>
        Monday-Friday 8AM-5PM <br>
        <a href="tel:+18162322710">(816) 232-2710</a></p>
      </div>
  </ul>
</div>
</nav>

{% block body_block %}

{% endblock %}

<div class="footer">
<table align='center'>
  <td valign="top">
    <p><u>Who we are</u> <br>We will sell you the car you need<br> and keep you on the road <br>with our exemplary service department.</p>
  </td>
  <td>
    <p><u>Associations</u></p>
    <img src="{% static 'info_app/images/oreilly.png' %}" alt="">
    <img src="{% static 'info_app/images/ase.png' %}" alt="">
    <img src="{% static 'info_app/images/cooper.png' %}" alt="">
    <img src="{% static 'info_app/images/Google-Plus-BG-transparent.png' %}" alt="">
    <img src="{% static 'info_app/images/tranlogo.png' %}" alt="">
    <img src="{% static 'info_app/images/presaward.png' %}" alt="">
  </td>
</table>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var url = window.location;
        $('ul.nav a[href="'+ url +'"]').parent().addClass('active');
        $('ul.nav a').filter(function() {
             return this.href == url;
        }).parent().addClass('active');
    });
</script>

</body>
</html>

info_app/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title_block %}
Avenue Auto - Home
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/index.css' %}">
{% endblock %}

{% block body_block %}

<!-- <div class="containermobile">
  <a href="https://www.facebook.com/St.JoeAvenueAutoSales/" target="_blank">
  <img class="center-block img-responsive" src="{% static 'info_app/images/Facebook_logo.png' %}" alt="No image" id="fbindex">
  </a>
  <div class="dropdown-divider"></div>
  <p><a href="http://maps.google.com/?q=1200 4202 St Joseph Ave, St Joseph, MO 64505" target="_blank">4202 St Joseph Ave<br> St Joseph, MO 64505</a> <br>
  Monday-Friday 8AM-5PM <br>
  <a href="tel:+18162322710">(816) 232-2710</a></p>
</div> -->

<div class="buildingcon">
  <img src="{% static 'info_app/images/building.jpg' %}" alt="" id="buildimg">
  <div class="text-block">
    <a href="https://www.facebook.com/St.JoeAvenueAutoSales/" target="_blank">
    <img class="center-block img-responsive" src="{% static 'info_app/images/Facebook_logo.png' %}" alt="No image" id="fbindex"></a>
    <div class="dropdown-divider"></div>
    <p><a href="http://maps.google.com/?q=1200 4202 St Joseph Ave, St Joseph, MO 64505" target="_blank">4202 St Joseph Ave, St Joseph, MO 64505</a> <br>
    Monday-Friday 8AM-5PM <br>
    <a href="tel:+18162322710">(816) 232-2710</a></p>
  </div>
</div>

<div class="row">
  <div class="col-md">
    <a href="{% url 'info_app:repairs' %}"><img src="{% static 'info_app/images/mechanics.jpg' %}" alt=""></a>
    <div class="bottom-left">Repairs</div>
  </div>
  <div class="col-md">
    <a href="{% url 'info_app:tires' %}"><img src="{% static 'info_app/images/tires.jpg' %}" alt=""></a>
    <div class="bottom-left">Tires</div>
  </div>
  <div class="col-md">
    <a href="{% url 'info_app:carlist' %}"><img src="{% static 'info_app/images/cars.jpg' %}" alt=""></a>
    <div class="bottom-left">Inventory</div>
  </div>
</div>

<!-- <script type="text/javascript" src="{% static '/info_app/js/index.js' %}"></script> -->

{% endblock %}

info_app/templates/info_app/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title_block %}
Avenue Auto - About
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/about.css' %}">
{% endblock %}

{% block body_block %}
{# <div class="container" id='conall'> #}
  <div class="container">
    <div class="jumbotron">
      <h2><strong>About Us</strong></h2>
      <div class="row">
        <div class="col-md-7">
        <h4><strong>Avenue Auto</strong> believes in earning and keeping each customer’s trust.
          The word we use is fairness.
          Ryan, Joe and Danny genuinely care about their customers.
          We honestly want the best for you.
          Nobody likes when their vehicle to break down, this is why our service and repair guarantees four values each of our customers know and have come to expect:
          <br><br>
          <b><span style="color:#32CD32">&#10004;</span> Correct diagnosis and repair<br>
          <span style="color:#32CD32">&#10004;</span> Economical solutions for repairs<br>
          <span style="color:#32CD32">&#10004;</span> Honesty<br>
          <span style="color:#32CD32">&#10004;</span> Warranties on every repair</b>
          <br><br>
          <em>We understand our business cannot grow without your trust.</em>
        </h4>
        </div>
        <div class="col-md-5">
          <img src="{% static 'info_app/images/building.jpg' %}" alt="">
          <p id='mech'>Joe and Ryan Eric</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h3><b>Ryan Erich</b> | Shop Manager</h3>
        <img src="{% static 'info_app/images/ryan.jpg' %}" alt="" class="img-fluid" align="right">
        <p>Ryan has over 22 year experience in the auto business and 15 of those have been with Avenue Auto.
          After graduating from technical school he received specialized certification through General Motors.
          Upon leaving the GM dealership we are honored he has chosen to continue his career with us.
          Since joing the team at Avenue Auto he has continued to pursue advanced certification specializing in Diagnostics and repair.
          He has the skills and expertise our customers have come to respect and relay on. Ryan’s slogan is:
          <em>Promises delivered. Quality Guaranteed.</em></p>
      </div>
      <div class="col-md-4">
        <h3><b>Joe Erich</b> | Head Technician</h3>
        <img src="{% static 'info_app/images/joe.jpg' %}" alt="" class="img-fluid" align="right">
        <p>Joe has been employed at Avenue Auto for 16 years. <em>We call Ryan and Joe the dynamic duo.</em>
          Joe stared his career with Ryan being trained through General Motors.
          We are also honored that Joe choose to work together running their own shop.
          You will find Joe has advanced knowledge in all systems of autos as well as advanced Diagnostic systems.
          Joe has continued to pursue advanced certifications to best serve our customers. Joe specializes in putting the “care” in Autocare.
          Joe’s slogan is: <em>I share the pride of your ride.</em></p>
      </div>
      <div class="col-md-4">
        <h3><b>Daniel Long</b> | Assistant Technician</h3>
        <img src="{% static 'info_app/images/danny.jpg' %}" alt="" class="img-fluid" align="right">
        <p>Daniel has 9 year experience in the service and repair business. He also has a passion for anything to do with cars.
          After his graduating from Technical School he worked for independent shops as well as a dealership.
          His certifications include Alignment, Suspension, Brakes, and AC systems.
          We are glad to have Daniel on staff helping our customers.
          Daniel’s slogan is: <em>Have your work done here and you'll never go anywhere else again.</em></p>
      </div>
    </div>
  </div>
  <br>
  <div class="container">
    <h3>Location:</h3>
    <iframe width="600" height="450" frameborder="0" style='border:0;display:flex;margin:auto' src="https://www.google.com/maps/embed/v1/place?q=Avenue%20Auto%20Saint%20Joseph&key=AIzaSyDiI-k4UCZ6qCzVYoWvfR3Y3FBYBGXSbXw" allowfullscreen></iframe>
  </div>
  <br>

{% endblock %}

info_app/templates/info_app/car_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title_block %}
Avenue Auto - Inventory
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/car_list.css' %}">
{% endblock %}


{% block body_block %}

<div class="container">
  <div class="w3-display-container" id='carlist'>
    {# <h1>Available Cars</h1> #}
      <div class="row">
      {% for car in car_list %}
      <div class="col-md-4">
      <a href="{{car.id}}/">
        <div id='cardiv'>
        <img src="{{car.headpic.url}}" class="w3-image w3-hover-opacity" alt="No Image">
        </div>
        <div class="w3-display-bottomleft w3-container">{{car.year}} {{car.make}} {{car.model}}</div>
        <!-- <div class="bottom-left">{{car.year}} {{car.make}} {{car.model}}</div> -->
      </a>
      </div>
      {% endfor %}
      </div>
  </div>

</div>



<!-- <script type="text/javascript" src='{% static '/info_app/js/car_list.js' %}'></script> -->

{% endblock %}

info_app/templates/info_app/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title_block %}
Avenue Auto - Inventory
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/detail.css' %}">
{% endblock %}

{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h2><strong>Details:</strong></h2>
    <p></p>
    <span id='cardetailspan'>
      <ul>
        <li><strong>Make:</strong> {{car_details.make}}</li>
        <li><strong>Model:</strong> {{car_details.model}}</li>
        <li><strong>Year:</strong> {{car_details.year}}</li>
        <li><strong>Mileage:</strong> {{car_details.mileage}}</li>
      </ul>
      <ul>
        <li><strong>Engine:</strong> {{car_details.engine}}</li>
        <li><strong>Transmission:</strong> {{car_details.transmission}}</li>
        <li><strong>Vin:</strong> {{car_details.vin}}</li>
      </ul>
      <ul id="pricelist">
        <li><strong>Warranty:</strong> 6 months or 6,000 miles</li>
        <li><strong>MSRP:</strong> {{car_details.MSRP}}</li>
        <li style="font-size:1.5em;color:green;"><strong>Sale Price:</strong> {{car_details.price}}</li>
        <li><strong>Savings:</strong> {{car_details.savings}}</li>
      </ul>
    </span>
    <p><strong>Features and trim level:</strong></p>
    <p>{{car_details.moreinfo|linebreaks}}</p>
    <p><b>The {{car_details.make}} {{car_details.model}} is backed by a 6-month or 6,000 mile warranty.</b></p>

  </div>
</div>

<div class="container">
  <div class="text-center">
    {% for carmedia in car_details.carpic.all %}
      <a class="lightbox" href="#carpiclight{{carmedia.id}}"><img class="center-block img-responsive w3-hover-opacity" id='carpic{{carmedia.id}}' src="{{ carmedia.pic.url }}" alt="No Image"></a>
    {% endfor %}
  </div>
</div>

{% for carmedia in car_details.carpic.all %}
<div class="lightbox-target" id="carpiclight{{carmedia.id}}">
  <img src="{{ carmedia.pic.url }}" alt="No Image">
  <a class="lightbox-close" href="#carpic{{carmedia.id}}"></a>
</div>
{% endfor %}

<script>
$(function() {
    $('#carlistnav').addClass("active");
});
</script>

{% endblock %}

info_app/templates/info_app/repairs.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title_block %}
Avenue Auto - Repairs
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/repairs.css' %}">
{% endblock %}

{% block body_block %}

<div class="container">
  <!-- <div class="jumbotron"> -->
    <p class="custlead" style="padding-top:5%;">We do it all!  Welcome to <span id='aaspan'>Avenue Auto</span> your one-stop, on-the-spot auto service headquarters for a complete line of quality services and auto repair. We have provided St Joseph with the best products and unprecedented services for everything we do.
    <br>At <span id='aaspan'>Avenue Auto</span> our technicians are qualified to work on domestic and import vehicles, and can handle just about any auto repair. In fact, we’ve often been able to diagnose and fix issues that other auto repair shops could not.
    <br>And since 2003, our customers have been coming back over and over again. Come fine out why.</p>
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-4">
          <img src="{% static 'info_app/images/certfiedautorepair.png' %}" id="warranty">
        </div>
        <div class="col-md-8">
          <h3>The Extra Mile | <span>Our 12 month, 12,000 mile Warranty</span></h3>
          <p class="custlead"></p><br>
          <p class="custlead" style="padding-bottom:5%;">We are a certified O’Reilly Auto Repair Center, which means all of our repairs and services will be covered by a 12 month, 12,000 mile warranty (or more). You can be confident we have you covered, here in our town and nationwide.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_strut.jpg' %}" alt="">
          <h2>Struts and Shocks</h2>
      </div>
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_battery.jpg' %}" alt="">
          <h2>Batteries and Electrical</h2>
      </div>
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_electric.jpg' %}" alt="">
          <h2>Diagnostics</h2>
      </div>
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_tune.jpg' %}" alt="">
          <h2>Tune Ups</h2>
      </div>
    </div>
    <div class="row" style="margin-bottom:30px;">
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_AC.jpg' %}" alt="">
          <h2>Air Conditioning Systems</h2>
      </div>
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_inspec.jpg' %}" alt="">
          <h2>Steering</h2>
      </div>
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_suspension.jpg' %}" alt="">
          <h2>Brakes and Suspensions</h2>
      </div>
      <div class="col-md-3 col-6">
          <img src="{% static 'info_app/images/rep_engine.jpg' %}" alt="">
          <h2>Engine and Transmission Replacements</h2>
      </div>
    </div>
</div>

{% endblock %}

info_app/templates/info_app/tires.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title_block %}
Avenue Auto - Tires
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'info_app/css/tires.css' %}">
{% endblock %}

{% block body_block %}

<div class="container">
    <p class="lead">
      No matter how many choices of tires there may be... We think buying tires should be simple.
      <br>We deliver what our customers needs and wants:
      <br><br><span id='listspan'><span style="color:#32CD32">&#10004;</span> Long-lasting</span>
      <br><span id='listspan'><span style="color:#32CD32">&#10004;</span> Affordably price</span>
      <br><span id='listspan'><span style="color:#32CD32">&#10004;</span> Roadside Assistance</span>
      <br><span id='listspan'><span style="color:#32CD32">&#10004;</span> Warranty</span>
      <br><br><span id='aaspan'><span id='aaspan'>Avenue Auto</span></span> provides it all. We have over 100,000 tires available for your car, truck, van or SUV. With its volume buying we pass along low prices to our customers.  <span id='aaspan'>Avenue Auto</span> inventory and low prices make it easy for you to find the tires you need by just one visit.
    </p>

    <div class="row">
      <div class="col-md-4">
        <img class="center-block img-responsive" src="{% static 'info_app/images/falkien.jpg' %}" alt="">
      </div>
      <div class="col-md-4">
        <img class="center-block img-responsive" src="{% static 'info_app/images/continental.jpg' %}" alt="">
      </div>
      <div class="col-md-4">
        <img class="center-block img-responsive" src="{% static 'info_app/images/dunlop.jpg' %}" alt="">
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <img class="center-block img-responsive" src="{% static 'info_app/images/kuhmo.jpg' %}" alt="">
      </div>
      <div class="col-md-4">
        <img class="center-block img-responsive" src="{% static 'info_app/images/pirelli.png' %}" alt="">
      </div>
      <div class="col-md-4">
        <img class="center-block img-responsive" src="{% static 'info_app/images/main_coopertire.jpg' %}" alt="">
      </div>
    </div>
    <h1><strong>TIRE SAVING COUPONS</strong></h1>
    <div class="coupon">
      <h2>$20 OFF SET OF TIRES...</h2>
      <div class="row">
        <div class="col-md-6">
            <img src="{% static 'info_app/images/tirespage.jpg' %}" alt="">
        </div>
        <div class="col-md-6">
          <span><img src="{% static 'info_app/images/money.jpg' %}" alt=""></span>
        </div>
      </div>
    </div>
    <div class="coupon">
      <h2>$20.00 OFF FRONT END ALIGNMENT... </h2>
      <div class="row">
        <div class="col-md-6">
            <img src="{% static 'info_app/images/tirespage.jpg' %}" alt="">
        </div>
        <div class="col-md-6">
          <span><img src="{% static 'info_app/images/money.jpg' %}" alt=""></span>
        </div>
      </div>
    </div>
    <div class="coupon">
      <h2>$25.95 ROTATION AND BALANCE...</h2>
      <div class="row">
        <div class="col-md-6">
            <img src="{% static 'info_app/images/tirespage.jpg' %}" alt="">
        </div>
        <div class="col-md-6">
          <img src="{% static 'info_app/images/money.jpg' %}" alt="">
        </div>
      </div>
    </div>

</div>


{% endblock %}